---

name: Integration
on:
    pull_request:
    push:
        branches:
            - master
            - main

jobs:
    integration:
        name: Integration
        runs-on: ubuntu-latest
        services:
            redis:
                image: redis
                ports:
                    - 6379:6379
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-go@v5

            - name: Build and run tests
              run: |
                go build
                go test ./...
